apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_dispatch:
    inputs:
      artifactName:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true
      url:
        type: string
        required: false
      digest:
        type: string
        required: false
env:
  NAMESPACE: microhacker
  APP_NAME: microhacker-api
jobs:
  deploy:
    environment: micro-hacker
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - uses: cashokannamalai/kubeconfig@v1
        name: Set kubeconfig
        with:
          secname: ${{ secrets.kubeconfig }}
      - id: install-chart
        name: Install helm chart
        uses: cloudbees-io/helm-install@v1
        with:
          chart-location: ${{ cloudbees.workspace }}/chart
          release-name: ${{ env.APP_NAME }}
          namespace: ${{ env.NAMESPACE }}
          values: |
            image:
              repository: ${{ secrets.DOCKERHUB_USER }}/hackers-api
              tag: latest
            hostname: microhacker-api.preview.cb-demos.io
      - name: Register deployed artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: ${{ secrets.DOCKERHUB_USER }}/hackers-api
          version: latest
          url: "${{ secrets.DOCKERHUB_USER }}/hackers-api:latest"
          target-environment: micro-hacker
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Deployed environment
            [Dev frontend](https://microhacker-api.preview.cb-demos.io/)

            Running hackers-api:${{ cloudbees.scm.sha }}
          format: MARKDOWN
